### ISSUE TITLE
Getting IOException

### ISSUE THREAD

**Issue by rahulr4** [Gridstone/RxStore#45] opened 2018-01-31 13:15 UTC
java.lang.RuntimeException: java.io.IOException: open failed: EROFS (Read-only file system)

I am trying to implement this using RxJava2. It was working fine in earlier version with RxJava!

Here is my piece of code :

`
 ListStore<SearchQuery> suggestionListStore = RxStore
                .list(new File("SearchSuggestion"), new GsonConverter(), SearchQuery.class);

        BaseNetworkSubscriber2<Object> baseNetworkSubscriber2 = suggestionListStore.get()
                .toObservable()
                .flatMap((Function<List<SearchQuery>, ObservableSource<?>>) searchQueries -> {
                    ArrayList<SearchQuery> searchQueries2 = new ArrayList<>(searchQueries);
                    searchQueries2.add(query);
                    Single<List<SearchQuery>> listSingle = suggestionListStore
                            .observePut(searchQueries2);
                    return listSingle.toObservable();
                }).subscribeWith(
                        new BaseNetworkSubscriber2<Object>(getView().getAppContextFromView()) {
                            @Override
                            public void onComplete() {
                                super.onComplete();
                            }

                            @Override
                            public void onError(Throwable e) {
                                super.onError(e);
                                e.printStackTrace();
                            }

                            @Override
                            public void onNext(Object o) {
                                super.onNext(o);
//                                getView().showRecentSearchSuggestion(suggestions);

                            }
                        });
        CompositeDisposable compositeDisposable = new CompositeDisposable();
        compositeDisposable.add(baseNetworkSubscriber2);`

**Comment by chris-horner** [comment] 2018-02-01 03:56
Hi there. Could you please post the entire stack trace? Would be good to see which line exactly is failing. From looking at this without the stack trace, getting a Read-only file system error seems to suggest that you've passed in a file you don't have write access to?

**Comment by rahulr4** [comment] 2018-02-01 05:20
The exact code is working with rxjava1 when i downgrade to the mentioned version 5.x but as soon as i upgraded it to 6.x it started crashing with the below log

`02-01 10:48:21.404 10499-10685/org.sluhn.Android E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-3
                                                                   Process: org.sluhn.Android, PID: 10499
                                                                   io.reactivex.exceptions.OnErrorNotImplementedException: java.io.IOException: open failed: EROFS (Read-only file system)
                                                                       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                       at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
                                                                       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
                                                                       at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:95)
                                                                       at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
                                                                       at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:42)
                                                                       at io.reactivex.Single.subscribe(Single.java:2779)
                                                                       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                    Caused by: java.lang.RuntimeException: java.io.IOException: open failed: EROFS (Read-only file system)
                                                                       at au.com.gridstone.rxstore.Utils.runInWriteLock(Utils.java:63)
                                                                       at au.com.gridstone.rxstore.RealListStore$2.subscribe(RealListStore.java:86)
                                                                       at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
                                                                       at io.reactivex.Single.subscribe(Single.java:2779) 
                                                                       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 
                                                                       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452) 
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61) 
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                       at java.lang.Thread.run(Thread.java:818) 
                                                                    Caused by: java.io.IOException: open failed: EROFS (Read-only file system)
                                                                       at java.io.File.createNewFile(File.java:939)
                                                                       at au.com.gridstone.rxstore.RealListStore$2$1.run(RealListStore.java:88)
                                                                       at au.com.gridstone.rxstore.Utils.runInWriteLock(Utils.java:61)
                                                                       at au.com.gridstone.rxstore.RealListStore$2.subscribe(RealListStore.java:86) 
                                                                       at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39) 
                                                                       at io.reactivex.Single.subscribe(Single.java:2779) 
                                                                       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 
                                                                       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452) 
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61) 
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                       at java.lang.Thread.run(Thread.java:818) 
                                                                    Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
                                                                       at libcore.io.Posix.open(Native Method)
                                                                       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                       at java.io.File.createNewFile(File.java:932)
                                                                       at au.com.gridstone.rxstore.RealListStore$2$1.run(RealListStore.java:88) 
                                                                       at au.com.gridstone.rxstore.Utils.runInWriteLock(Utils.java:61) 
                                                                       at au.com.gridstone.rxstore.RealListStore$2.subscribe(RealListStore.java:86) 
                                                                       at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39) 
                                                                       at io.reactivex.Single.subscribe(Single.java:2779) 
                                                                       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 
                                                                       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452) 
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61) 
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                       at java.lang.Thread.run(Thread.java:818) `

**Comment by rahulr4** [comment] 2018-02-01 05:24
and even after implementing onError, this error still comes. It is something about read write lock

**Comment by chris-horner** [comment] 2018-02-01 06:45
I created the following unit test, attempting to match your code path. (Our unit tests are in Kotlin, but hopefully you get the idea).
```kotlin
val store = newTestStore()
val list = listOf(TestData("1", 1))
store.put(list, Schedulers.trampoline())

store.get()
    .toObservable()
    .flatMap { store.observePut(it.plus(TestData("2", 2))).toObservable() }
    .subscribe { storedList ->
      assertThat(storedList).isEqualTo(listOf(TestData("1", 1), TestData("2", 2)))
    }
```
This unit test passes just fine.

From the stack trace, I see that the crash is occurring *inside* the `readWriteLock`, so it's not the lock that's preventing it from running. The code that's crashing inside of RxStore is
```java
if (!file.exists() && !file.createNewFile()) {
  throw new IOException("Could not create file for store.");
}
```
It's crashing when attempting to make the file. I see when you make the list store you pass in
```java
new File("SearchSuggestion")
```
This is not something I've tried doing on Android, as I always specify the directory I would like the store file to exist in. Specifically, I make use of `context.getFilesDir()`, so my RxStores use a file that looks like
```java
new File(context.getFilesDir(), "SearchSuggestions")
```
Is it possible that your application is trying to create the file in a directory it doesn't have write permission to? Have you tried using the files directory `Context` provides?

**Comment by siddharthuohyd** [comment] 2018-02-01 07:16
Yes I have created the context.getFilesDir() and given the write permission also but still getting the same issue.This issue arises when I have update the library from 5.0 to 6.0.In previous everything is working fine.

**Comment by chris-horner** [comment] 2018-02-01 07:25
Are you able to create a unit test or a small sample project that reproduces this issue? I'm unable to recreate this with the unit test I posted above.

**Comment by rahulr4** [comment] 2018-02-01 07:40
So i made this small utility class copying only the File creation elements from last version and using this for 6.x versions. It is working now

`

import android.content.Context;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Type;

import org.jetbrains.annotations.NotNull;

import au.com.gridstone.rxstore.Converter;
import au.com.gridstone.rxstore.ListStore;
import au.com.gridstone.rxstore.RxStore;
import au.com.gridstone.rxstore.ValueStore;
import rx.Scheduler;

public final class StoreProvider {

    private final Converter converter;
    private File directory;

    private StoreProvider(File directory, Converter converter) {
        this.directory = directory;
        this.converter = converter;
    }

    private File getFileForStore(String key) {
        if (!directory.exists()) {
            if (!directory.mkdir()) {
                throw new RuntimeException("Could not create directory for store.");
            }
        }

        File file = new File(directory, key);

        if (!file.exists()) {
            try {
                if (!file.createNewFile()) {
                    throw new IOException("Could not create file for store.");
                }
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }

        return file;
    }

    public @NotNull
    <T> ValueStore<T> valueStore(@NotNull String key, @NotNull Type type) {
        return RxStore.value(getFileForStore(key), converter, type);
    }

    @NotNull
    public <T> ListStore<T> listStore(@NotNull String key, @NotNull Type type) {
        return RxStore
                .list(getFileForStore(key), converter,
                        type);
    }

    @NotNull
    public static AndroidBuilder withContext(@NotNull Context context) {
        return new AndroidBuilder(context);
    }

    public static final class AndroidBuilder {

        private final Context context;
        private String directoryName = "";

        private AndroidBuilder(@NotNull Context context) {
            this.context = context.getApplicationContext();
        }

        /**
         * By default, a StoreProvider will instantiate all stores with a single thread executor
         * {@link Scheduler} to ensure items get written and read in order. If you would like to
         * override this behaviour (such as for testing with {@link Schedulers#immediate()}), then
         * you can specify a custom Scheduler here.
         */
        /**
         * Specify a subdirectory that this {@link StoreProvider} will use to save and
         * restore objects.
         */
        @NotNull
        public AndroidBuilder inDir(@NotNull String directory) {
            this.directoryName = directory;
            return this;
        }

        /**
         * <p>
         * This will also finish initializing this StoreProvider instance.
         */
        public @NotNull
        StoreProvider using(@NotNull Converter converter) {
            File directory = context.getDir(directoryName, Context.MODE_PRIVATE);
            return new StoreProvider(directory, converter);
        }
    }
}
`

**Comment by chris-horner** [comment] 2018-02-01 22:03
The difference between the v1 and v2 code is that in v1 you had to specify a parent directory for store files to be written to. In v2 you just specify a file. Because v1 managed that parent directory, it ensured it existed before writing to it. In your original code, did you guarantee that the directory existed for the store files you were trying to create?

**Comment by chris-horner** [comment] 2018-02-12 22:16
Closing this, as no further information has been provided by the reporter.

**Closed by chris-horner** 2018-02-12 22:16 UTC
